out_dir: dynn_results
metric_best: accuracy
tensorboard_each_run: True  # Log to Tensorboard each run
accelerator: "cuda:0"
mlflow:
  use: True
  project: Exp
  name: mnist-GRIT-RRWP
wandb:
  use: False
  project: MNIST
dataset:
  pe_transform_on_the_fly: True # compute PE on the fly to save memory when launching many experiments in parallel
  format: PyG-GNNBenchmarkDataset
  name: MNIST
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
posenc_RRWP:
  enable: True
  ksteps: 18
  add_identity: True
  add_node_attr: False
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_period: 2
  enable_ckpt: True  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: True  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
  ckpt_clean: True
model:
  type: GritTransformer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:  # Hyperparameters optimized for ~100k budget.
  layer_type: GritTransformer
  layers: 5
  n_heads: 4
  dim_hidden: 52  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  layer_norm: False
  batch_norm: True
  update_e: True
  attn_dropout: 0.5
  attn:
    clamp: 5.
    act: 'relu'
    full_attn: True
    edge_enhance: True
    O_e: True
    norm_e: True
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 52  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: False
  act: relu
  dropout: 0.1
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: sgd
  weight_decay: 5e-4
  base_lr: 0.002
  max_epoch: 9
  scheduler: cosine_with_warmup
pretrained:
  dir: results/mnist-GRIT-RRWP-LARGE
  freeze_main: True